SELECT
    l.cldf_id as wals_code,
    l.cldf_iso639P3code as iso_code,
    l.cldf_glottocode as glottocode,
    l.cldf_name as Name,
    l.cldf_latitude as latitude,
    l.cldf_longitude as longitude,
    l.Genus as genus,
    l.Family as family,
    l.cldf_macroarea as macroarea,
max(case when v.cldf_parameterReference = '100A' then c.Number || ' ' || c.cldf_name end) as '100A Alignment of Verbal Person Marking',
max(case when v.cldf_parameterReference = '101A' then c.Number || ' ' || c.cldf_name end) as '101A Expression of Pronominal Subjects',
max(case when v.cldf_parameterReference = '102A' then c.Number || ' ' || c.cldf_name end) as '102A Verbal Person Marking',
max(case when v.cldf_parameterReference = '103A' then c.Number || ' ' || c.cldf_name end) as '103A Third Person Zero of Verbal Person Marking',
max(case when v.cldf_parameterReference = '104A' then c.Number || ' ' || c.cldf_name end) as '104A Order of Person Markers on the Verb',
max(case when v.cldf_parameterReference = '105A' then c.Number || ' ' || c.cldf_name end) as '105A Ditransitive Constructions: The Verb "Give"',
max(case when v.cldf_parameterReference = '106A' then c.Number || ' ' || c.cldf_name end) as '106A Reciprocal Constructions',
max(case when v.cldf_parameterReference = '107A' then c.Number || ' ' || c.cldf_name end) as '107A Passive Constructions',
max(case when v.cldf_parameterReference = '108A' then c.Number || ' ' || c.cldf_name end) as '108A Antipassive Constructions',
max(case when v.cldf_parameterReference = '108B' then c.Number || ' ' || c.cldf_name end) as '108B Productivity of the Antipassive Construction',
max(case when v.cldf_parameterReference = '109A' then c.Number || ' ' || c.cldf_name end) as '109A Applicative Constructions',
max(case when v.cldf_parameterReference = '109B' then c.Number || ' ' || c.cldf_name end) as '109B Other Roles of Applied Objects',
max(case when v.cldf_parameterReference = '10A' then c.Number || ' ' || c.cldf_name end) as '10A Vowel Nasalization',
max(case when v.cldf_parameterReference = '10B' then c.Number || ' ' || c.cldf_name end) as '10B Nasal Vowels in West Africa',
max(case when v.cldf_parameterReference = '110A' then c.Number || ' ' || c.cldf_name end) as '110A Periphrastic Causative Constructions',
max(case when v.cldf_parameterReference = '111A' then c.Number || ' ' || c.cldf_name end) as '111A Nonperiphrastic Causative Constructions',
max(case when v.cldf_parameterReference = '112A' then c.Number || ' ' || c.cldf_name end) as '112A Negative Morphemes',
max(case when v.cldf_parameterReference = '113A' then c.Number || ' ' || c.cldf_name end) as '113A Symmetric and Asymmetric Standard Negation',
max(case when v.cldf_parameterReference = '114A' then c.Number || ' ' || c.cldf_name end) as '114A Subtypes of Asymmetric Standard Negation',
max(case when v.cldf_parameterReference = '115A' then c.Number || ' ' || c.cldf_name end) as '115A Negative Indefinite Pronouns and Predicate Negation',
max(case when v.cldf_parameterReference = '116A' then c.Number || ' ' || c.cldf_name end) as '116A Polar Questions',
max(case when v.cldf_parameterReference = '117A' then c.Number || ' ' || c.cldf_name end) as '117A Predicative Possession',
max(case when v.cldf_parameterReference = '118A' then c.Number || ' ' || c.cldf_name end) as '118A Predicative Adjectives',
max(case when v.cldf_parameterReference = '119A' then c.Number || ' ' || c.cldf_name end) as '119A Nominal and Locational Predication',
max(case when v.cldf_parameterReference = '11A' then c.Number || ' ' || c.cldf_name end) as '11A Front Rounded Vowels',
max(case when v.cldf_parameterReference = '120A' then c.Number || ' ' || c.cldf_name end) as '120A Zero Copula for Predicate Nominals',
max(case when v.cldf_parameterReference = '121A' then c.Number || ' ' || c.cldf_name end) as '121A Comparative Constructions',
max(case when v.cldf_parameterReference = '122A' then c.Number || ' ' || c.cldf_name end) as '122A Relativization on Subjects',
max(case when v.cldf_parameterReference = '123A' then c.Number || ' ' || c.cldf_name end) as '123A Relativization on Obliques',
max(case when v.cldf_parameterReference = '124A' then c.Number || ' ' || c.cldf_name end) as '124A "Want" Complement Subjects',
max(case when v.cldf_parameterReference = '125A' then c.Number || ' ' || c.cldf_name end) as '125A Purpose Clauses',
max(case when v.cldf_parameterReference = '126A' then c.Number || ' ' || c.cldf_name end) as '126A "When" Clauses',
max(case when v.cldf_parameterReference = '127A' then c.Number || ' ' || c.cldf_name end) as '127A Reason Clauses',
max(case when v.cldf_parameterReference = '128A' then c.Number || ' ' || c.cldf_name end) as '128A Utterance Complement Clauses',
max(case when v.cldf_parameterReference = '129A' then c.Number || ' ' || c.cldf_name end) as '129A Hand and Arm',
max(case when v.cldf_parameterReference = '12A' then c.Number || ' ' || c.cldf_name end) as '12A Syllable Structure',
max(case when v.cldf_parameterReference = '130A' then c.Number || ' ' || c.cldf_name end) as '130A Finger and Hand',
max(case when v.cldf_parameterReference = '130B' then c.Number || ' ' || c.cldf_name end) as '130B Cultural Categories of Languages with Identity of "Finger" and "Hand"',
max(case when v.cldf_parameterReference = '131A' then c.Number || ' ' || c.cldf_name end) as '131A Numeral Bases',
max(case when v.cldf_parameterReference = '132A' then c.Number || ' ' || c.cldf_name end) as '132A Number of Non-Derived Basic Colour Categories',
max(case when v.cldf_parameterReference = '133A' then c.Number || ' ' || c.cldf_name end) as '133A Number of Basic Colour Categories',
max(case when v.cldf_parameterReference = '134A' then c.Number || ' ' || c.cldf_name end) as '134A Green and Blue',
max(case when v.cldf_parameterReference = '135A' then c.Number || ' ' || c.cldf_name end) as '135A Red and Yellow',
max(case when v.cldf_parameterReference = '136A' then c.Number || ' ' || c.cldf_name end) as '136A M-T Pronouns',
max(case when v.cldf_parameterReference = '136B' then c.Number || ' ' || c.cldf_name end) as '136B M in First Person Singular',
max(case when v.cldf_parameterReference = '137A' then c.Number || ' ' || c.cldf_name end) as '137A N-M Pronouns',
max(case when v.cldf_parameterReference = '137B' then c.Number || ' ' || c.cldf_name end) as '137B M in Second Person Singular',
max(case when v.cldf_parameterReference = '138A' then c.Number || ' ' || c.cldf_name end) as '138A Tea',
max(case when v.cldf_parameterReference = '139A' then c.Number || ' ' || c.cldf_name end) as '139A Irregular Negatives in Sign Languages',
max(case when v.cldf_parameterReference = '13A' then c.Number || ' ' || c.cldf_name end) as '13A Tone',
max(case when v.cldf_parameterReference = '140A' then c.Number || ' ' || c.cldf_name end) as '140A Question Particles in Sign Languages',
max(case when v.cldf_parameterReference = '141A' then c.Number || ' ' || c.cldf_name end) as '141A Writing Systems',
max(case when v.cldf_parameterReference = '142A' then c.Number || ' ' || c.cldf_name end) as '142A Para-Linguistic Usages of Clicks',
max(case when v.cldf_parameterReference = '143A' then c.Number || ' ' || c.cldf_name end) as '143A Order of Negative Morpheme and Verb',
max(case when v.cldf_parameterReference = '143B' then c.Number || ' ' || c.cldf_name end) as '143B Obligatory Double Negation',
max(case when v.cldf_parameterReference = '143C' then c.Number || ' ' || c.cldf_name end) as '143C Optional Double Negation',
max(case when v.cldf_parameterReference = '143D' then c.Number || ' ' || c.cldf_name end) as '143D Optional Triple Negation',
max(case when v.cldf_parameterReference = '143E' then c.Number || ' ' || c.cldf_name end) as '143E Preverbal Negative Morphemes',
max(case when v.cldf_parameterReference = '143F' then c.Number || ' ' || c.cldf_name end) as '143F Postverbal Negative Morphemes',
max(case when v.cldf_parameterReference = '143G' then c.Number || ' ' || c.cldf_name end) as '143G Minor morphological means of signaling negation',
max(case when v.cldf_parameterReference = '144A' then c.Number || ' ' || c.cldf_name end) as '144A Position of Negative Word With Respect to Subject, Object, and Verb',
max(case when v.cldf_parameterReference = '144B' then c.Number || ' ' || c.cldf_name end) as '144B Position of negative words relative to beginning and end of clause and with respect to adjacency to verb',
max(case when v.cldf_parameterReference = '144C' then c.Number || ' ' || c.cldf_name end) as '144C Languages with different word order in negative clauses',
max(case when v.cldf_parameterReference = '144D' then c.Number || ' ' || c.cldf_name end) as '144D The Position of Negative Morphemes in SVO Languages',
max(case when v.cldf_parameterReference = '144E' then c.Number || ' ' || c.cldf_name end) as '144E Multiple Negative Constructions in SVO Languages',
max(case when v.cldf_parameterReference = '144F' then c.Number || ' ' || c.cldf_name end) as '144F Obligatory Double Negation in SVO languages',
max(case when v.cldf_parameterReference = '144G' then c.Number || ' ' || c.cldf_name end) as '144G Optional Double Negation in SVO languages',
max(case when v.cldf_parameterReference = '144H' then c.Number || ' ' || c.cldf_name end) as '144H NegSVO Order',
max(case when v.cldf_parameterReference = '144I' then c.Number || ' ' || c.cldf_name end) as '144I SNegVO Order',
max(case when v.cldf_parameterReference = '144J' then c.Number || ' ' || c.cldf_name end) as '144J SVNegO Order',
max(case when v.cldf_parameterReference = '144K' then c.Number || ' ' || c.cldf_name end) as '144K SVONeg Order',
max(case when v.cldf_parameterReference = '144L' then c.Number || ' ' || c.cldf_name end) as '144L The Position of Negative Morphemes in SOV Languages',
max(case when v.cldf_parameterReference = '144M' then c.Number || ' ' || c.cldf_name end) as '144M Multiple Negative Constructions in SOV Languages',
max(case when v.cldf_parameterReference = '144N' then c.Number || ' ' || c.cldf_name end) as '144N Obligatory Double Negation in SOV languages',
max(case when v.cldf_parameterReference = '144O' then c.Number || ' ' || c.cldf_name end) as '144O Optional Double Negation in SOV languages',
max(case when v.cldf_parameterReference = '144P' then c.Number || ' ' || c.cldf_name end) as '144P NegSOV Order',
max(case when v.cldf_parameterReference = '144Q' then c.Number || ' ' || c.cldf_name end) as '144Q SNegOV Order',
max(case when v.cldf_parameterReference = '144R' then c.Number || ' ' || c.cldf_name end) as '144R SONegV Order',
max(case when v.cldf_parameterReference = '144S' then c.Number || ' ' || c.cldf_name end) as '144S SOVNeg Order',
max(case when v.cldf_parameterReference = '144T' then c.Number || ' ' || c.cldf_name end) as '144T The Position of Negative Morphemes in Verb-Initial Languages',
max(case when v.cldf_parameterReference = '144U' then c.Number || ' ' || c.cldf_name end) as '144U Double negation in verb-initial languages',
max(case when v.cldf_parameterReference = '144V' then c.Number || ' ' || c.cldf_name end) as '144V Verb-Initial with Preverbal Negative',
max(case when v.cldf_parameterReference = '144W' then c.Number || ' ' || c.cldf_name end) as '144W Verb-Initial with Negative that is Immediately Postverbal or between Subject and Object',
max(case when v.cldf_parameterReference = '144X' then c.Number || ' ' || c.cldf_name end) as '144X Verb-Initial with Clause-Final Negative',
max(case when v.cldf_parameterReference = '144Y' then c.Number || ' ' || c.cldf_name end) as '144Y The Position of Negative Morphemes in Object-Initial Languages',
max(case when v.cldf_parameterReference = '14A' then c.Number || ' ' || c.cldf_name end) as '14A Fixed Stress Locations',
max(case when v.cldf_parameterReference = '15A' then c.Number || ' ' || c.cldf_name end) as '15A Weight-Sensitive Stress',
max(case when v.cldf_parameterReference = '16A' then c.Number || ' ' || c.cldf_name end) as '16A Weight Factors in Weight-Sensitive Stress Systems',
max(case when v.cldf_parameterReference = '17A' then c.Number || ' ' || c.cldf_name end) as '17A Rhythm Types',
max(case when v.cldf_parameterReference = '18A' then c.Number || ' ' || c.cldf_name end) as '18A Absence of Common Consonants',
max(case when v.cldf_parameterReference = '19A' then c.Number || ' ' || c.cldf_name end) as '19A Presence of Uncommon Consonants',
max(case when v.cldf_parameterReference = '1A' then c.Number || ' ' || c.cldf_name end) as '1A Consonant Inventories',
max(case when v.cldf_parameterReference = '20A' then c.Number || ' ' || c.cldf_name end) as '20A Fusion of Selected Inflectional Formatives',
max(case when v.cldf_parameterReference = '21A' then c.Number || ' ' || c.cldf_name end) as '21A Exponence of Selected Inflectional Formatives',
max(case when v.cldf_parameterReference = '21B' then c.Number || ' ' || c.cldf_name end) as '21B Exponence of Tense-Aspect-Mood Inflection',
max(case when v.cldf_parameterReference = '22A' then c.Number || ' ' || c.cldf_name end) as '22A Inflectional Synthesis of the Verb',
max(case when v.cldf_parameterReference = '23A' then c.Number || ' ' || c.cldf_name end) as '23A Locus of Marking in the Clause',
max(case when v.cldf_parameterReference = '24A' then c.Number || ' ' || c.cldf_name end) as '24A Locus of Marking in Possessive Noun Phrases',
max(case when v.cldf_parameterReference = '25A' then c.Number || ' ' || c.cldf_name end) as '25A Locus of Marking: Whole-language Typology',
max(case when v.cldf_parameterReference = '25B' then c.Number || ' ' || c.cldf_name end) as '25B Zero Marking of A and P Arguments',
max(case when v.cldf_parameterReference = '26A' then c.Number || ' ' || c.cldf_name end) as '26A Prefixing vs. Suffixing in Inflectional Morphology',
max(case when v.cldf_parameterReference = '27A' then c.Number || ' ' || c.cldf_name end) as '27A Reduplication',
max(case when v.cldf_parameterReference = '28A' then c.Number || ' ' || c.cldf_name end) as '28A Case Syncretism',
max(case when v.cldf_parameterReference = '29A' then c.Number || ' ' || c.cldf_name end) as '29A Syncretism in Verbal Person/Number Marking',
max(case when v.cldf_parameterReference = '2A' then c.Number || ' ' || c.cldf_name end) as '2A Vowel Quality Inventories',
max(case when v.cldf_parameterReference = '30A' then c.Number || ' ' || c.cldf_name end) as '30A Number of Genders',
max(case when v.cldf_parameterReference = '31A' then c.Number || ' ' || c.cldf_name end) as '31A Sex-based and Non-sex-based Gender Systems',
max(case when v.cldf_parameterReference = '32A' then c.Number || ' ' || c.cldf_name end) as '32A Systems of Gender Assignment',
max(case when v.cldf_parameterReference = '33A' then c.Number || ' ' || c.cldf_name end) as '33A Coding of Nominal Plurality',
max(case when v.cldf_parameterReference = '34A' then c.Number || ' ' || c.cldf_name end) as '34A Occurrence of Nominal Plurality',
max(case when v.cldf_parameterReference = '35A' then c.Number || ' ' || c.cldf_name end) as '35A Plurality in Independent Personal Pronouns',
max(case when v.cldf_parameterReference = '36A' then c.Number || ' ' || c.cldf_name end) as '36A The Associative Plural',
max(case when v.cldf_parameterReference = '37A' then c.Number || ' ' || c.cldf_name end) as '37A Definite Articles',
max(case when v.cldf_parameterReference = '38A' then c.Number || ' ' || c.cldf_name end) as '38A Indefinite Articles',
max(case when v.cldf_parameterReference = '39A' then c.Number || ' ' || c.cldf_name end) as '39A Inclusive/Exclusive Distinction in Independent Pronouns',
max(case when v.cldf_parameterReference = '39B' then c.Number || ' ' || c.cldf_name end) as '39B Inclusive/Exclusive Forms in Pama-Nyungan',
max(case when v.cldf_parameterReference = '3A' then c.Number || ' ' || c.cldf_name end) as '3A Consonant-Vowel Ratio',
max(case when v.cldf_parameterReference = '40A' then c.Number || ' ' || c.cldf_name end) as '40A Inclusive/Exclusive Distinction in Verbal Inflection',
max(case when v.cldf_parameterReference = '41A' then c.Number || ' ' || c.cldf_name end) as '41A Distance Contrasts in Demonstratives',
max(case when v.cldf_parameterReference = '42A' then c.Number || ' ' || c.cldf_name end) as '42A Pronominal and Adnominal Demonstratives',
max(case when v.cldf_parameterReference = '43A' then c.Number || ' ' || c.cldf_name end) as '43A Third Person Pronouns and Demonstratives',
max(case when v.cldf_parameterReference = '44A' then c.Number || ' ' || c.cldf_name end) as '44A Gender Distinctions in Independent Personal Pronouns',
max(case when v.cldf_parameterReference = '45A' then c.Number || ' ' || c.cldf_name end) as '45A Politeness Distinctions in Pronouns',
max(case when v.cldf_parameterReference = '46A' then c.Number || ' ' || c.cldf_name end) as '46A Indefinite Pronouns',
max(case when v.cldf_parameterReference = '47A' then c.Number || ' ' || c.cldf_name end) as '47A Intensifiers and Reflexive Pronouns',
max(case when v.cldf_parameterReference = '48A' then c.Number || ' ' || c.cldf_name end) as '48A Person Marking on Adpositions',
max(case when v.cldf_parameterReference = '49A' then c.Number || ' ' || c.cldf_name end) as '49A Number of Cases',
max(case when v.cldf_parameterReference = '4A' then c.Number || ' ' || c.cldf_name end) as '4A Voicing in Plosives and Fricatives',
max(case when v.cldf_parameterReference = '50A' then c.Number || ' ' || c.cldf_name end) as '50A Asymmetrical Case-Marking',
max(case when v.cldf_parameterReference = '51A' then c.Number || ' ' || c.cldf_name end) as '51A Position of Case Affixes',
max(case when v.cldf_parameterReference = '52A' then c.Number || ' ' || c.cldf_name end) as '52A Comitatives and Instrumentals',
max(case when v.cldf_parameterReference = '53A' then c.Number || ' ' || c.cldf_name end) as '53A Ordinal Numerals',
max(case when v.cldf_parameterReference = '54A' then c.Number || ' ' || c.cldf_name end) as '54A Distributive Numerals',
max(case when v.cldf_parameterReference = '55A' then c.Number || ' ' || c.cldf_name end) as '55A Numeral Classifiers',
max(case when v.cldf_parameterReference = '56A' then c.Number || ' ' || c.cldf_name end) as '56A Conjunctions and Universal Quantifiers',
max(case when v.cldf_parameterReference = '57A' then c.Number || ' ' || c.cldf_name end) as '57A Position of Pronominal Possessive Affixes',
max(case when v.cldf_parameterReference = '58A' then c.Number || ' ' || c.cldf_name end) as '58A Obligatory Possessive Inflection',
max(case when v.cldf_parameterReference = '58B' then c.Number || ' ' || c.cldf_name end) as '58B Number of Possessive Nouns',
max(case when v.cldf_parameterReference = '59A' then c.Number || ' ' || c.cldf_name end) as '59A Possessive Classification',
max(case when v.cldf_parameterReference = '5A' then c.Number || ' ' || c.cldf_name end) as '5A Voicing and Gaps in Plosive Systems',
max(case when v.cldf_parameterReference = '60A' then c.Number || ' ' || c.cldf_name end) as '60A Genitives, Adjectives and Relative Clauses',
max(case when v.cldf_parameterReference = '61A' then c.Number || ' ' || c.cldf_name end) as '61A Adjectives without Nouns',
max(case when v.cldf_parameterReference = '62A' then c.Number || ' ' || c.cldf_name end) as '62A Action Nominal Constructions',
max(case when v.cldf_parameterReference = '63A' then c.Number || ' ' || c.cldf_name end) as '63A Noun Phrase Conjunction',
max(case when v.cldf_parameterReference = '64A' then c.Number || ' ' || c.cldf_name end) as '64A Nominal and Verbal Conjunction',
max(case when v.cldf_parameterReference = '65A' then c.Number || ' ' || c.cldf_name end) as '65A Perfective/Imperfective Aspect',
max(case when v.cldf_parameterReference = '66A' then c.Number || ' ' || c.cldf_name end) as '66A The Past Tense',
max(case when v.cldf_parameterReference = '67A' then c.Number || ' ' || c.cldf_name end) as '67A The Future Tense',
max(case when v.cldf_parameterReference = '68A' then c.Number || ' ' || c.cldf_name end) as '68A The Perfect',
max(case when v.cldf_parameterReference = '69A' then c.Number || ' ' || c.cldf_name end) as '69A Position of Tense-Aspect Affixes',
max(case when v.cldf_parameterReference = '6A' then c.Number || ' ' || c.cldf_name end) as '6A Uvular Consonants',
max(case when v.cldf_parameterReference = '70A' then c.Number || ' ' || c.cldf_name end) as '70A The Morphological Imperative',
max(case when v.cldf_parameterReference = '71A' then c.Number || ' ' || c.cldf_name end) as '71A The Prohibitive',
max(case when v.cldf_parameterReference = '72A' then c.Number || ' ' || c.cldf_name end) as '72A Imperative-Hortative Systems',
max(case when v.cldf_parameterReference = '73A' then c.Number || ' ' || c.cldf_name end) as '73A The Optative',
max(case when v.cldf_parameterReference = '74A' then c.Number || ' ' || c.cldf_name end) as '74A Situational Possibility',
max(case when v.cldf_parameterReference = '75A' then c.Number || ' ' || c.cldf_name end) as '75A Epistemic Possibility',
max(case when v.cldf_parameterReference = '76A' then c.Number || ' ' || c.cldf_name end) as '76A Overlap between Situational and Epistemic Modal Marking',
max(case when v.cldf_parameterReference = '77A' then c.Number || ' ' || c.cldf_name end) as '77A Semantic Distinctions of Evidentiality',
max(case when v.cldf_parameterReference = '78A' then c.Number || ' ' || c.cldf_name end) as '78A Coding of Evidentiality',
max(case when v.cldf_parameterReference = '79A' then c.Number || ' ' || c.cldf_name end) as '79A Suppletion According to Tense and Aspect',
max(case when v.cldf_parameterReference = '79B' then c.Number || ' ' || c.cldf_name end) as '79B Suppletion in Imperatives and Hortatives',
max(case when v.cldf_parameterReference = '7A' then c.Number || ' ' || c.cldf_name end) as '7A Glottalized Consonants',
max(case when v.cldf_parameterReference = '80A' then c.Number || ' ' || c.cldf_name end) as '80A Verbal Number and Suppletion',
max(case when v.cldf_parameterReference = '81A' then c.Number || ' ' || c.cldf_name end) as '81A Order of Subject, Object and Verb',
max(case when v.cldf_parameterReference = '81B' then c.Number || ' ' || c.cldf_name end) as '81B Languages with two Dominant Orders of Subject, Object, and Verb',
max(case when v.cldf_parameterReference = '82A' then c.Number || ' ' || c.cldf_name end) as '82A Order of Subject and Verb',
max(case when v.cldf_parameterReference = '83A' then c.Number || ' ' || c.cldf_name end) as '83A Order of Object and Verb',
max(case when v.cldf_parameterReference = '84A' then c.Number || ' ' || c.cldf_name end) as '84A Order of Object, Oblique, and Verb',
max(case when v.cldf_parameterReference = '85A' then c.Number || ' ' || c.cldf_name end) as '85A Order of Adposition and Noun Phrase',
max(case when v.cldf_parameterReference = '86A' then c.Number || ' ' || c.cldf_name end) as '86A Order of Genitive and Noun',
max(case when v.cldf_parameterReference = '87A' then c.Number || ' ' || c.cldf_name end) as '87A Order of Adjective and Noun',
max(case when v.cldf_parameterReference = '88A' then c.Number || ' ' || c.cldf_name end) as '88A Order of Demonstrative and Noun',
max(case when v.cldf_parameterReference = '89A' then c.Number || ' ' || c.cldf_name end) as '89A Order of Numeral and Noun',
max(case when v.cldf_parameterReference = '8A' then c.Number || ' ' || c.cldf_name end) as '8A Lateral Consonants',
max(case when v.cldf_parameterReference = '90A' then c.Number || ' ' || c.cldf_name end) as '90A Order of Relative Clause and Noun',
max(case when v.cldf_parameterReference = '90B' then c.Number || ' ' || c.cldf_name end) as '90B Prenominal relative clauses',
max(case when v.cldf_parameterReference = '90C' then c.Number || ' ' || c.cldf_name end) as '90C Postnominal relative clauses',
max(case when v.cldf_parameterReference = '90D' then c.Number || ' ' || c.cldf_name end) as '90D Internally-headed relative clauses',
max(case when v.cldf_parameterReference = '90E' then c.Number || ' ' || c.cldf_name end) as '90E Correlative relative clauses',
max(case when v.cldf_parameterReference = '90F' then c.Number || ' ' || c.cldf_name end) as '90F Adjoined relative clauses',
max(case when v.cldf_parameterReference = '90G' then c.Number || ' ' || c.cldf_name end) as '90G Double-headed relative clauses',
max(case when v.cldf_parameterReference = '91A' then c.Number || ' ' || c.cldf_name end) as '91A Order of Degree Word and Adjective',
max(case when v.cldf_parameterReference = '92A' then c.Number || ' ' || c.cldf_name end) as '92A Position of Polar Question Particles',
max(case when v.cldf_parameterReference = '93A' then c.Number || ' ' || c.cldf_name end) as '93A Position of Interrogative Phrases in Content Questions',
max(case when v.cldf_parameterReference = '94A' then c.Number || ' ' || c.cldf_name end) as '94A Order of Adverbial Subordinator and Clause',
max(case when v.cldf_parameterReference = '95A' then c.Number || ' ' || c.cldf_name end) as '95A Relationship between the Order of Object and Verb and the Order of Adposition and Noun Phrase',
max(case when v.cldf_parameterReference = '96A' then c.Number || ' ' || c.cldf_name end) as '96A Relationship between the Order of Object and Verb and the Order of Relative Clause and Noun',
max(case when v.cldf_parameterReference = '97A' then c.Number || ' ' || c.cldf_name end) as '97A Relationship between the Order of Object and Verb and the Order of Adjective and Noun',
max(case when v.cldf_parameterReference = '98A' then c.Number || ' ' || c.cldf_name end) as '98A Alignment of Case Marking of Full Noun Phrases',
max(case when v.cldf_parameterReference = '99A' then c.Number || ' ' || c.cldf_name end) as '99A Alignment of Case Marking of Pronouns',
max(case when v.cldf_parameterReference = '9A' then c.Number || ' ' || c.cldf_name end) as '9A The Velar Nasal'
FROM
    LanguageTable as l
    JOIN ValueTable as v ON l.cldf_id = v.cldf_languageReference
    JOIN CodeTable as c ON v.cldf_codeReference = c.cldf_id
GROUP BY
    l.cldf_id,
    l.cldf_iso639P3code,
    l.cldf_glottocode,
    l.cldf_name,
    l.cldf_latitude,
    l.cldf_longitude,
    l.Genus,
    l.Family,
    l.cldf_macroarea
ORDER BY
    l.cldf_id
;
